"""ORM model for pipeline-generated artifacts."""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import String, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.experiment import Run


class Artifact(Base):
    """A file generated by a pipeline run — linked to its producing run.

    Types: markdown | audio | metrics | traces
    Storage keys follow the pattern: {run_id}/{artifact_type}/{filename}
    id, created_at, updated_at are inherited from Base.
    """

    __tablename__ = "artifacts"

    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("runs.id"), nullable=False
    )
    artifact_type: Mapped[str] = mapped_column(String(32), nullable=False)
    storage_key: Mapped[str] = mapped_column(String(1024), nullable=False)

    run: Mapped[Run] = relationship("Run", back_populates="artifacts")
